/**
 * Danh sách metadata âm nhạc truyền thống — dùng chung cho UploadMusic và ResearcherPortalPage.
 * Single source of truth: chỉnh tại đây sẽ đồng bộ cho toàn bộ app.
 */

export const ETHNICITIES = [
  "Kinh",
  "Tày",
  "Thái",
  "Mường",
  "Khmer",
  "H'Mông",
  "Nùng",
  "Hoa",
  "Dao",
  "Gia Rai",
  "Ê Đê",
  "Ba Na",
  "Xơ Đăng",
  "Sán Chay",
  "Cơ Ho",
  "Chăm",
  "Sán Dìu",
  "Hrê",
  "Mnông",
  "Ra Glai",
  "Giáy",
  "Stră",
  "Bru-Vân Kiều",
  "Cơ Tu",
  "Giẻ Triêng",
  "Tà Ôi",
  "Mạ",
  "Khơ Mú",
  "Co",
  "Chơ Ro",
  "Hà Nhì",
  "Xinh Mun",
  "Chu Ru",
  "Lào",
  "La Chí",
  "Kháng",
  "Phù Lá",
  "La Hủ",
  "La Ha",
  "Pà Thẻn",
  "Lự",
  "Ngái",
  "Chứt",
  "Lô Lô",
  "Mảng",
  "Cờ Lao",
  "Bố Y",
  "Cống",
  "Si La",
  "Pu Péo",
  "Rơ Măm",
  "Brâu",
  "Ơ Đu",
  "Khác",
];

export const REGIONS = [
  "Trung du và miền núi Bắc Bộ",
  "Đồng bằng Bắc Bộ",
  "Bắc Trung Bộ",
  "Nam Trung Bộ",
  "Cao nguyên Trung Bộ",
  "Đông Nam Bộ",
  "Tây Nam Bộ",
];

export const EVENT_TYPES = [
  "Đám cưới",
  "Đám tang",
  "Lễ hội đình",
  "Lễ hội chùa",
  "Tết Nguyên đán",
  "Hội xuân",
  "Lễ cầu mùa",
  "Lễ cúng tổ tiên",
  "Lễ cấp sắc",
  "Lễ hội đâm trâu",
  "Lễ hội cồng chiêng",
  "Sinh hoạt cộng đồng",
  "Biểu diễn nghệ thuật",
  "Ghi âm studio",
  "Ghi âm thực địa",
  "Khác",
];

export const INSTRUMENTS = [
  "Alal (Ba Na)",
  "Aráp (Ba Na)",
  "Aráp (Ca Dong)",
  "Aráp (Gia Rai)",
  "Aráp (Rơ Năm)",
  "Aráp (Stră)",
  "Biên khánh (Kinh)",
  "Bro (Ba Na)",
  "Bro (Gia Rai)",
  "Bro (Giẻ Triêng)",
  "Bro (Xơ Đăng)",
  "Bẳng bu (Thái)",
  "Chul (Ba Na)",
  "Chul (Gia Rai)",
  "Chênh Kial (Ba Na)",
  "Cò ke (Mường)",
  "Cồng, chiêng (Ba Na)",
  "Cồng, chiêng (Gia Rai)",
  "Cồng, chiêng (Giẻ Triêng)",
  "Cồng, chiêng (Hrê)",
  "Cồng, chiêng (Ê Đê)",
  "Dàn nhạc ngũ âm (Khmer)",
  "Goong (Ba Na)",
  "Goong (Gia Rai)",
  "Goong (Giẻ Triêng)",
  "Goong đe (Ba Na)",
  "Hơgơr (Ê Đê)",
  "Hơgơr cân (Mnâm)",
  "Hơgơr cân (Rơ Năm)",
  "Hơgơr prong (Gia Rai)",
  "Hơgơr tuôn (Hà Lang)",
  "Hơgơr tăk (Ba Na)",
  "Khinh khung (Ba Na)",
  "Khinh khung (Gia Rai)",
  "Khèn (H'Mông)",
  "Khèn (Ta Ôi)",
  "Khèn (Ê Đê)",
  "Khên (Vân Kiều)",
  "Knăh ring (Ba Na)",
  "Knăh ring (Gia Rai)",
  "K'lông put (Gia Rai)",
  "K'ny (Ba Na)",
  "K'ny (Gia Rai)",
  "K'ny (Rơ Ngao)",
  "K'ny (Xơ Đăng)",
  "Kèn bầu (Chăm)",
  "Kèn bầu (Kinh)",
  "Kèn bầu (Thái)",
  "Kềnh (H'Mông)",
  "M'linh (Dao)",
  "M'linh (Mường)",
  "M'nhum (Gia Rai)",
  "Mõ (Kinh)",
  "Phách (Kinh)",
  "Pí cổng (Thái)",
  "Pí lè (Thái)",
  "Pí lè (Tày)",
  "Pí một lao (Kháng)",
  "Pí một lao (Khơ Mú)",
  "Pí một lao (La Ha)",
  "Pí một lao (Thái)",
  "Pí pặp (Thái)",
  "Pí phướng (Thái)",
  "Pí đôi (Thái)",
  "Púa (H'Mông)",
  "Púa (Lô Lô)",
  "Qeej (H'Mông)",
  "Rang leh (Ca Dong)",
  "Rang leh (Stră)",
  "Rang rai (Ba Na)",
  "Rang rai (Gia Rai)",
  "Song lang (Kinh)",
  "Sáo ngang (Kinh)",
  "Sênh tiền (Kinh)",
  "T'rum (Gia Rai)",
  "Ta in (Hà Nhì)",
  "Ta lư (Vân Kiều)",
  "Ta pòl (Ba Na)",
  "Ta pòl (Brâu)",
  "Ta pòl (Gia Rai)",
  "Ta pòl (Rơ Năm)",
  "Tam thập lục (Kinh)",
  "Teh ding (Gia Rai)",
  "Tiêu (Kinh)",
  "Tol alao (Ca Dong)",
  "Tông đing (Ba Na)",
  "Tông đing (Ca Dong)",
  "Tơ nốt (Ba Na)",
  "Trống bộc (Kinh)",
  "Trống cái (Kinh)",
  "Trống chầu (Kinh)",
  "Trống cơm (Kinh)",
  "Trống dẹt (Kinh)",
  "Trống khẩu (Kinh)",
  "Trống lắng (Kinh)",
  "Trống mảnh (Kinh)",
  "Trống quần (Kinh)",
  "Trống đế (Kinh)",
  "Trống đồng (Kinh)",
  "Tính tẩu (Thái)",
  "Tính tẩu (Tày)",
  "Vang (Gia Rai)",
  "Đinh Duar (Giẻ Triêng)",
  "Đinh Khén (Xơ Đăng)",
  "Đinh tuk (Ba Na)",
  "Đao đao (Khơ Mú)",
  "Đuk đik (Giẻ Triêng)",
  "Đàn bầu (Kinh)",
  "Đàn môi (H'Mông)",
  "Đàn nguyệt (Kinh)",
  "Đàn nhị (Chăm)",
  "Đàn nhị (Dao)",
  "Đàn nhị (Giáy)",
  "Đàn nhị (Kinh)",
  "Đàn nhị (Nùng)",
  "Đàn nhị (Tày)",
  "Đàn t'rưng (Ba Na)",
  "Đàn t'rưng (Gia Rai)",
  "Đàn tam (Kinh)",
  "Đàn tranh (Kinh)",
  "Đàn tứ (Kinh)",
  "Đàn tỳ bà (Kinh)",
  "Đàn đá (Kinh)",
  "Đàn đáy (Kinh)",
];
